config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'users/new'
  get 'users/create'
  get  'signup',    to: 'users#new'
  post 'signup',    to: 'users#create'
  get  'login',     to: 'sessions#new'
  post 'login',     to: 'sessions#create'
  get  'logout',    to: 'sessions#destroy'
  get  'new_event', to: 'events#new'
  post 'new_event', to: 'events#create'
  post 'events/:id/attend', as: 'attend', to: 'events#attend'
  resources :events
  resources :users
  get '*path', to: 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: "attended_event_id"
  has_many :attendees, through: :attendances

  validates :title, presence: true
  validates :location, presence: true
  validates :date, presence: true

  default_scope {order(date: :desc)}
  scope :previous_events, -> { where("date < ?", Time.now)}
  scope :upcoming_events, -> { where("date > ?", Time.now)}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendances, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, except: [:show, :index]

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      @event.attendees << @event.creator
      flash[:success] = "Created new event."
      redirect_to @event
    else
      flash[:warning] = "Cannot create event"
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def index
    @events = Event.paginate(page: params[:page], per_page: 6)
  end
  
  def attend
    Event.find_by(id: params[:id]).attendees << current_user
    flash[:success] = "You're now attending this event!"
    redirect_to event_path
  end

  private

      def event_params
        params.require(:event).permit(:title, :location, :date)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "Logged in successfully."
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:warning] = "Cannot login."
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    flash[:success] = "Logged out."
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to root_url if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created."
      redirect_to @user
    else
      flash.now[:danger] = "Cannot create user."
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end
  private

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Returns true if a user is logged in
  def logged_in?
    !current_user.nil?
  end

  # Returns the current user if any
  def current_user
    User.find_by(id: session[:user_id])
  end

  # Logs out the user
  def logout
    session[:user_id] = nil
  end

  def require_login
    if !logged_in?
      flash[:warning] = "You should be logged in for this action!"
      redirect_to root_url
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend_status.html.erb
<% if !logged_in? %>
  <p>
    <%= link_to "Login", login_path %> or 
    <%= link_to "Signup", signup_path %> now
    to attend this event!
  </p>
<% elsif @event.date.past? %>
  <p>This event is passed!</p>
<% elsif @event.attendees.include? current_user %>
  <p>You're attending this event!</p>
<% else %>
  <%= button_to 'Attend', attend_path, method: :post,
                          data: { confirm: "You are attending '#{@event.title}'." },
                          class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/events/_event.html.erb
<div class="card event-card <%= "event-card-past" if (event.date.past?)%>">
  <img class="card-img-top" src="https://picsum.photos/246/160?random=<%=event.id%>" alt="Event image">
  <div class="card-body">
    <h5 class="card-title"><%= event.title %></h5>
    <p class="card-text">
      This is the description text of the event.
      <%= event.title %> event will be located at <%= event.location %>.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    </p>
    <span class="badge badge-pill badge-info"><%= event.attendees.count %> Attending</span>
    <p class="card-text">Created by <%= event.creator.name %> </p>
  </div>
  <div class="card-footer clearfix">
    <small class="text-muted float-left"><%= event.date %></small>
    <a class="btn btn-sm btn-primary float-right"
       href="<%= event_path(event) %>">
      Details
    </a>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for @event , url: new_event_path do |f| %>
  <%= f.label :title %>
  <%= f.text_area :title, class: 'form-control' %>
  
  <%= f.submit 'Create Event', class: 'btn btn-primary' %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="jumbotron">
  <%= will_paginate @events %>

  <h1>All Events</h1>
  <div class="card-columns">
    <%= render @events %>
  </div>

  <%= will_paginate @events %>

</div>

app/views/events/new.html.erb
<div class="col-md-6 text-center m-auto pt-3">
  <h1>New Event</h1>
  <p>The event's creator will be seen as <strong><%= current_user.name %></strong></p>

  <%= form_for @event , url: new_event_path do |f| %>
    <div class="form-group">
    <%= f.text_field :title, placeholder: "Name of the event", class: 'form-control form-control-lg row' %>
    <%= f.text_field :location, placeholder: "Where will it be?", class: 'form-control form-control-lg row' %>
    <%= f.date_field :date, class: 'form-control form-control-lg row' %>
    <%= f.submit 'Create Event', class: 'btn btn-primary row' %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="jumbotron text-left">
<div class="row">
  <div class="col-md-9">
    <h1><%= @event.title %></h2>
    <h3 class="font-italic">by <%= @event.creator.name %></h3>
    <p class="font-weight-bold mb-1">Description</p>
    <p class="text-justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis voluptate aspernatur dolorum quia? Saepe quisquam possimus suscipit earum! Quis vero natus numquam deleniti quidem illum suscipit sapiente vel, perspiciatis culpa. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sint ea libero, maxime reiciendis id, odit incidunt quod esse mollitia optio quo molestiae voluptatum, asperiores fugit nihil in consequatur! Recusandae, alias!</p>
    <p class="font-weight-bold mb-1">Location</p>
    <p><%= @event.location %></p>
    <p class="font-weight-bold mb-1">Date</p>
    <p><%= @event.date %></p>
  </div>
  <div class="col-md-3 border-left">
    <p class="font-weight-bold mt-3 mb-1">
      Attendees <span class="badge badge-pill badge-success"><%= @event.attendees.size %></span>
    </p>
    <% if @event.attendees.any? %>
      <ul>
      <% @event.attendees.take(10).each do |e| %>
        <li><%= e.name %></li>
      <% end %>
      <% "..." if @event.attendees.size > 10 %>
      </ul>
    <% end %>
    <%= render 'attend_status' %>
  </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-#{name}" %>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small">
  <%= link_to "(home)", root_url%>
  <%= link_to "(back)", :back %>
  <%= link_to "(events)", events_url %>
  <%= link_to "(logout)", logout_url, data: { confirm: "You are logging out!" }, class: "float-right" if logged_in? %>
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= root_path %>">PRIVATE EVENTS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarText" aria-controls="navbarText"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= events_path %>">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">New Event</a>
      </li>
    </ul>
    <span class="navbar-text">
      <% if logged_in?%>
      Logged in, <%= link_to current_user.name, user_path(current_user) %>
      <% end %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_list_group.html.erb
<% if object.any? %>
  <ul class="list-group">
    <% object.each do |e| %>
      <a href="<%= event_path(e) %>"
      class="list-group-item list-group-item-action">
        <%= e.title %>
      </a>
    <% end %>
  </ul>
<% else %>
  <em>(None)</em>
<% end %>

app/views/static_pages/index.html.erb
<% if !logged_in? %>
<div class="jumbotron p-2 text-left">
  <div class="row">
    <div class="col-md-9">
      <h1>Private Events</h1>
      <p>Choose an event to attend, or event create one to invite people.</p>
    </div>
    <div class="col-md-3 m-auto border-left">
      
        <a href="<%= signup_path %>" class="btn btn-primary btn-lg">
          Signup
        </a>
        <a href="<%= login_path %>" class="btn btn-secondary btn-lg">
          Login
        </a>
    </div>
  </div>
</div>
<% end %>
  <h1>Upcoming Events</h1>
  
  
    <% if Event.upcoming_events.any? %>
      <div class="card-group">
        <%= render Event.upcoming_events.take(3) %>
      </div>
    <% elsif Event.previous_events.any? %>
      <p>Could not find any new events this time. Here are some past events.</p>
      <div class="card-group">
        <%= render Event.previous_events.take(3) %>
      </div>
    <% else %>
      <p>No events yet.</p>
    <% end %>
 
</div>

app/views/users/_created_events.html.erb
<% if @user.created_events.any? %>
    <div class="list-group col-md-6 m-auto">
      <% @user.created_events.each do |event| %>
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start m-1">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= event.title %></h5>
          <small><%= "Not defined" || event.date.utc %></small>
        </div>
        <p class="mb-1">It will be at <%= event.location %></p>
        <small>Click for details.</small>
        </a>
      <% end %>
    </div>
  <% else %>
    <p><em>None</em></p>
  <% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: signup_path do |f| %>
  <div class="form-group row">
    <div class="col-sm-2"><%= f.label :name, class: "col-form-label" %></div>
    <div class="col-sm-10"><%= f.text_field :name, class: 'form-control'%></div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2"><%= f.label :email, class: "col-form-label" %></div>
    <div class="col-sm-10"><%= f.email_field :email, class: 'form-control'%></div>
  </div>
  <div class="form-group row"> 
    <div class="col-sm-2"><%= f.label :password, class: "col-form-label" %></div>
    <div class="col-sm-10"><%= f.password_field :password, class: 'form-control'%></div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2"><%= f.label :password_confirmation, "Confirm", class: "col-form-label" %></div>
    <div class="col-sm-10"><%= f.password_field :password_confirmation, class: 'form-control'%></div>
  </div>
  <div class="row">
    <%= f.submit 'Create User', class: 'btn btn-primary m-auto'%>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="col-md-6 text-center m-auto pt-3">
  <h1>Let's get started</h1>
  <p>Create an account easily</p>
  <div class="text-left">
  <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron text-left">
  <div class="row">
    <div class="col-md-9">
      <h1><%= @user.name %></h2>
      <small class="font-italic">email: <%= @user.email %></small>
      <h4>Created Events</h4>
      <%= render 'shared/list_group', object: @user.created_events %>
    </div>
  </div>
  <div class="row border-top pt-2">
    <div class="col-md-9">
      <h4>Attending Soon</h4>
      <%= render 'shared/list_group', object: @user.attended_events.upcoming_events %>
    </div>
    <div class="col-md-3 border-left">
      <h5>Attended</h5>
      <%= render 'shared/list_group', object: @user.attended_events.previous_events %>
    </div>
  </div>
</div>